import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between mb-12 border-b border-slate-300 p-4">
          <h1 className="font-bold text-lg text-slate-800">Calender</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
